version: 2.1

orbs: 
  gradle: circleci/gradle@2.2.0

executors: 
  openjdk:
    docker:
      - image: cimg/openjdk:17.0

jobs: 
  create-distribution:
    executor: openjdk
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run:
                name: Create distribution
                command: ./gradlew ":app:assembleDist"
      - store_artifacts: 
          path: app/build/distributions/

workflows: 
  all-tests:
    jobs:
      - gradle/test:
          name: api-test
          test_command: ":api:test"
          test_results_path: api/build/test-results/ 
          reports_path: api/build/reports/
          executor: openjdk

      - gradle/test:
          name: impl-test
          test_command: ":impl:test"
          test_results_path: impl/build/test-results/
          reports_path: impl/build/reports/
          executor: openjdk
          requires:
            - api-test

      - gradle/test:
          name: app-test
          test_command: ":app:test"
          test_results_path: app/build/test-results/
          reports_path: app/build/reports/
          executor: openjdk
          requires:
            - api-test
            - impl-test

  run-app:
    jobs:
      - gradle/run:
          name: run
          executor: openjdk
          command: ":app:run"

  distribution:
    jobs:
      - create-distribution
